= OpenShift Workshop Operator


== Overview

This is an https://coreos.com/operators/[Kubernetes Operator^] to install the infrastructure for running 
OpenShift Workshops.

[IMPORTANT]
====
This operator has been tested on **OpenShift Container Platform 4.2** 
with **N preconfigured users (user1, user2, ..., userN)**. 
====

== Deploy the Operator

[IMPORTANT]
====
Please use an OpenShift user with **cluster-admin** privileges
====

=== Run it from your local environment

Perform the following tasks:

[source,bash]
----
cd openshift-workshop-operator
oc login
export OPERATOR_NAME=openshift-workshop-operator
oc create -f deploy/crds/openshift_v1alpha1_workshop_crd.yaml
oc new-project workshop-infra
operator-sdk up local --namespace=workshop-infra
----

=== Deploy it on OpenShift

Perform the following tasks:

[source,bash]
----
cd openshift-workshop-operator
oc login
oc new-project workshop-infra
oc apply -n workshop-infra -f deploy/service_account.yaml
oc apply -n workshop-infra -f deploy/cluster_role.yaml
oc apply -n workshop-infra -f deploy/cluster_role_binding.yaml
oc apply -n workshop-infra -f deploy/crds/openshift_v1alpha1_workshop_crd.yaml
oc apply -n workshop-infra -f deploy/operator.yaml
----

== Install the Workshop Infrastructure

The Workshop Infrastructure is deployed by creating a Custom Resource based on the **WorkShop** Custom Resource Definition. 
There is examples of custom resources (CR) in https://github.com/mcouliba/openshift-workshop-operator/tree/master/deploy/crds[crds]

For instance, to deploy the Workshop Infrastruture for the Cloud-Native Workshop,
please execute the following command:

[source,bash]
----
oc create -n workshop-infra -f deploy/crds/cloud_native_workshop_cr.yaml 
----

== Development

=== Requirements

* OpenShift 4.2
* Operator-SDK v0.8.0
* Docker

=== Build and Push the Operator Image

[source,bash]
----
cd openshift-workshop-operator
./buildImage.sh quay.io/mcouliba/openshift-workshop-operator:latest
----
