// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workshop) DeepCopyInto(out *Workshop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workshop.
func (in *Workshop) DeepCopy() *Workshop {
	if in == nil {
		return nil
	}
	out := new(Workshop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workshop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopList) DeepCopyInto(out *WorkshopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workshop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopList.
func (in *WorkshopList) DeepCopy() *WorkshopList {
	if in == nil {
		return nil
	}
	out := new(WorkshopList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkshopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopSpec) DeepCopyInto(out *WorkshopSpec) {
	*out = *in
	out.Etherpad = in.Etherpad
	out.Gogs = in.Gogs
	out.Nexus = in.Nexus
	out.ServiceMesh = in.ServiceMesh
	out.Guide = in.Guide
	out.Workspaces = in.Workspaces
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopSpec.
func (in *WorkshopSpec) DeepCopy() *WorkshopSpec {
	if in == nil {
		return nil
	}
	out := new(WorkshopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopSpecEtherpad) DeepCopyInto(out *WorkshopSpecEtherpad) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopSpecEtherpad.
func (in *WorkshopSpecEtherpad) DeepCopy() *WorkshopSpecEtherpad {
	if in == nil {
		return nil
	}
	out := new(WorkshopSpecEtherpad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopSpecGogs) DeepCopyInto(out *WorkshopSpecGogs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopSpecGogs.
func (in *WorkshopSpecGogs) DeepCopy() *WorkshopSpecGogs {
	if in == nil {
		return nil
	}
	out := new(WorkshopSpecGogs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopSpecGuide) DeepCopyInto(out *WorkshopSpecGuide) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopSpecGuide.
func (in *WorkshopSpecGuide) DeepCopy() *WorkshopSpecGuide {
	if in == nil {
		return nil
	}
	out := new(WorkshopSpecGuide)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopSpecNexus) DeepCopyInto(out *WorkshopSpecNexus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopSpecNexus.
func (in *WorkshopSpecNexus) DeepCopy() *WorkshopSpecNexus {
	if in == nil {
		return nil
	}
	out := new(WorkshopSpecNexus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopSpecServiceMesh) DeepCopyInto(out *WorkshopSpecServiceMesh) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopSpecServiceMesh.
func (in *WorkshopSpecServiceMesh) DeepCopy() *WorkshopSpecServiceMesh {
	if in == nil {
		return nil
	}
	out := new(WorkshopSpecServiceMesh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopSpecWorkspaces) DeepCopyInto(out *WorkshopSpecWorkspaces) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopSpecWorkspaces.
func (in *WorkshopSpecWorkspaces) DeepCopy() *WorkshopSpecWorkspaces {
	if in == nil {
		return nil
	}
	out := new(WorkshopSpecWorkspaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopStatus) DeepCopyInto(out *WorkshopStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopStatus.
func (in *WorkshopStatus) DeepCopy() *WorkshopStatus {
	if in == nil {
		return nil
	}
	out := new(WorkshopStatus)
	in.DeepCopyInto(out)
	return out
}
